app = "major-project-cse"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  image = "python:3.11-slim"

[env]
  # Your OpenRouteService API key
  ORS_API_KEY = "eyJvcmciOiI1YjNjZTM1OTc4NTExMTAwMDFjZjYyNDgiLCJpZCI6IjY1MjRkYmE3NGMwMzQ1ZmViOGEzYmViOGJkYzUzN2Y1IiwiaCI6Im11cm11cjY0In0="


[experimental]
  allowed_public_ports = [8080]
  auto_rollback = true

[deploy]
  release_command = ""

[http_service]
  internal_port = 8080
  force_https = true
